//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointments
    {
        public int id { get; set; }
        public string extra { get; set; }
        public Nullable<int> patient_id { get; set; }
        public Nullable<int> doc_id { get; set; }
        public Nullable<System.DateTime> appday { get; set; }
    
        public virtual docs docs { get; set; }
        public virtual patients patients { get; set; }
    }
}
